-- =========================================================
-- APIS AI — Supabase migration: system_prompts
-- ---------------------------------------------------------
-- Run this once in Supabase (SQL Editor, or `supabase db push`
-- if you use the CLI). Safe to re-run: every statement uses
-- IF NOT EXISTS / OR REPLACE / DROP...IF EXISTS guards.
-- =========================================================

create table if not exists public.system_prompts (
  id          bigint generated by default as identity primary key,
  name        text not null,
  prompt      text not null,
  is_active   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------
-- Only ONE prompt may be active at a time.
-- A plain unique index can't express "unique when true", so
-- we use a partial unique index on is_active, scoped to the
-- rows where is_active = true.
-- ---------------------------------------------------------
create unique index if not exists system_prompts_only_one_active
  on public.system_prompts (is_active)
  where is_active = true;

-- ---------------------------------------------------------
-- Keep updated_at current on every UPDATE.
-- ---------------------------------------------------------
create or replace function public.set_system_prompts_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_system_prompts_updated_at on public.system_prompts;
create trigger trg_system_prompts_updated_at
  before update on public.system_prompts
  for each row
  execute function public.set_system_prompts_updated_at();

-- ---------------------------------------------------------
-- Row Level Security.
-- The backend (api/chat.js) reads with the public ANON key,
-- never the service_role key, so RLS must explicitly allow
-- reading ONLY the active prompt. No INSERT/UPDATE/DELETE
-- policy is created for anon/authenticated — manage prompts
-- from the Supabase Table Editor (or with the service_role
-- key from a trusted admin context) only.
-- ---------------------------------------------------------
alter table public.system_prompts enable row level security;

drop policy if exists "Public can read active system prompt" on public.system_prompts;
create policy "Public can read active system prompt"
  on public.system_prompts
  for select
  using (is_active = true);

-- ---------------------------------------------------------
-- Seed: the prompt Apis AI already used before this change,
-- inserted as the active row so behavior doesn't change until
-- someone edits it in Supabase.
-- ---------------------------------------------------------
insert into public.system_prompts (name, prompt, is_active)
select
  'default',
  $$Kamu adalah Apis AI, asisten AI yang ramah, jelas, dan membantu di dalam aplikasi chat bernama "Apis AI" (Development by Apis).
Jawab dalam Bahasa Indonesia kecuali pengguna menulis dalam bahasa lain.
Gunakan format markdown ringan (heading, list, code block, tabel) bila relevan agar mudah dibaca di dalam bubble chat.
Jika pengguna mengirim gambar, amati isinya dan jawab sesuai konteks gambar tersebut.$$,
  true
where not exists (select 1 from public.system_prompts);
